/**
 * SISTEMA PARA TIENDA EN LÍNEA
 * Módulo: Módulo 4 - Soporte Técnico
 * Historia de Usuario: US015-A Asistente virtual (Chatbot FAQ)
 * AUTOR (Responsable): Zaeimind Navarrete
 * COPILOTO (XP Pair): Leonides Lopez Robles.
 * FECHA: 04/03/2026 
 */

import { getChatbotResponse } from '../../../src/services/support/chatbotService';
import { PrismaClient } from '@prisma/client';

// Mockeo interno para evitar ReferenceError y problemas de hoisting
jest.mock('@prisma/client', () => {
  const mockInternal = {
    faqKnowledge: {
      findFirst: jest.fn(),
      update: jest.fn(),
    },
  };
  return {
    PrismaClient: jest.fn(() => mockInternal),
  };
});

describe('US015-A: Pruebas Unitarias - Chatbot FAQ', () => {
  const prisma = new PrismaClient() as any;

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('Debe devolver la respuesta correcta si encuentra una coincidencia', async () => {
    // Simulamos que encuentra una pregunta sobre devoluciones
    prisma.faqKnowledge.findFirst.mockResolvedValue({
      id: 'faq-1',
      question: '¿Cómo hago una devolución?',
      answer: 'Debes ir a la sección de mis pedidos...',
      category: 'devoluciones'
    });

    const result = await getChatbotResponse('devolución');

    expect(result.answer).toContain('sección de mis pedidos');
    expect(result.isAutoGenerated).toBe(true);
    // Verificamos que se intente actualizar el contador de uso
    expect(prisma.faqKnowledge.update).toHaveBeenCalled();
  });

  it('Debe dar una respuesta por defecto si no hay coincidencias', async () => {
    prisma.faqKnowledge.findFirst.mockResolvedValue(null);

    const result = await getChatbotResponse('¿Cómo ganar dinero gratis?');

    expect(result.answer).toContain('no encontré una respuesta automática');
    expect(prisma.faqKnowledge.update).not.toHaveBeenCalled();
  });
});