/**
 * SISTEMA PARA TIENDA EN LÍNEA
 * Módulo: Módulo 4 - Soporte Técnico
 * Historia de Usuario: US015-A Asistente virtual (Chatbot FAQ)
 * AUTOR (Responsable): Zaeimind Navarrete
 * COPILOTO (XP Pair): Leonides Lopez Robles.
 * FECHA: 04/03/2026 
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const getChatbotResponse = async (userQuery: string) => {
  // 1. Buscar una respuesta en la base de conocimientos (FaqKnowledge)
  const match = await prisma.faqKnowledge.findFirst({
    where: {
      question: {
        contains: userQuery,
      }
    }
  });

  if (!match) {
    return {
      answer: "Lo siento, no encontré una respuesta automática. ¿Deseas hablar con un agente humano?",
      isAutoGenerated: true
    };
  }

  // 2. XP: Diseño Simple - Actualizar métrica de uso del FAQ
  await prisma.faqKnowledge.update({
    where: { id: match.id },
    data: { times_used: { increment: 1 } }
  });

  return {
    answer: match.answer,
    category: match.category,
    isAutoGenerated: true
  };
};